Allow new props from Lunatic
InseeFr/Lunatic-DSFR pull request #101
Opened 2023-09-18 13:48 UTC by isMattCoding

see https://github.com/InseeFr/Lunatic/pull/663

2023-09-18 13:52 UTC, Grafikart requested changes
Tu peux regarder la structure lunatic pour éviter d'avoir à utiliser les évènements (onClose) en utilisant directement un bouton. J'ai fait une PR au niveau de react/dsfr pour pouvoir ajouter un attribut value justement

2023-09-18 13:52 UTC, Grafikart commented on src/Modal.tsx
> +import { ReactEventHandler, MouseEventHandler, RefObject } from "react";
Quand tu n'utilise que des types tu peux mettre "import type" ça peut aider le compilateur

2023-09-18 13:52 UTC, Grafikart commented on src/Modal.tsx
> +    console.log(props);
A retirer

2023-09-18 14:52 UTC, isMattCoding commented
This change is dependant on this pr https://github.com/InseeFr/Lunatic/pull/663

2023-09-19 20:28 UTC, Grafikart approved these changes
Tout bon

2023-09-20 14:08 UTC, merged